### ISSUE TITLE
Moonfire crash

### ISSUE THREAD

**Issue by dolfs** [scottlamb/moonfire-nvr#46]
Found a crash tonight. This is probably an FYI and sort of duplicate of another issue regarding lack of robustness of the server against malformed API urls. At the time of this crash I was experiment with code and may have requested /api/cameras/<uuid>/view.mp4 without any query parameters.

```
Mar  9 23:23:33 moonfire moonfire-nvr[19022]: syncer moonfire_nvr::db] reserved 76201128-68f3-4ae4-a38d-265aec54a825
Mar  9 23:23:46 moonfire moonfire-nvr[19022]: syncer moonfire_nvr::dir] Back: deleting 10382181 bytes in 1 recordings (8773611 bytes needed)
Mar  9 23:23:46 moonfire moonfire-nvr[19022]: syncer moonfire_nvr::db] reserved 78bc3dda-2f20-4d27-b56f-fb1ced4cf4b8
Mar  9 23:24:01 moonfire moonfire-nvr[19022]: syncer moonfire_nvr::db] reserved 7f276a69-5eab-41a0-b39b-3e6511502f4f
Mar  9 23:24:11 moonfire moonfire-nvr[19022]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
Mar  9 23:24:12 moonfire moonfire-nvr[19022]: stack backtrace:
Mar  9 23:24:12 moonfire moonfire-nvr[19022]: 0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 1: std::sys_common::backtrace::_print
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/sys_common/backtrace.rs:71
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 2: std::panicking::default_hook::{{closure}}
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/sys_common/backtrace.rs:60
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panicking.rs:381
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 3: std::panicking::default_hook
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panicking.rs:397
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 4: std::panicking::rust_panic_with_hook
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panicking.rs:611
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 5: std::panicking::begin_panic
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panicking.rs:572
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 6: std::panicking::begin_panic_fmt
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panicking.rs:522
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 7: rust_begin_unwind
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panicking.rs:498
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 8: core::panicking::panic_fmt
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libcore/panicking.rs:71
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 9: core::panicking::panic
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: at ./checkout/src/libcore/panicking.rs:51
Mar  9 23:24:13 moonfire moonfire-nvr[19022]: 10: moonfire_nvr::mp4::FileBuilder::append_moov
Mar  9 23:24:17 moonfire moonfire-nvr[19022]: syncer moonfire_nvr::dir] Front Right: deleting 22786394 bytes in 1 recordings (15704467 bytes needed)
Mar  9 23:24:17 moonfire moonfire-nvr[19022]: syncer moonfire_nvr::db] reserved 58228b76-59c7-4781-a7d6-2dbe6b6d2f76
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./checkout/src/libcore/macros.rs:32
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at src/mp4.rs:1050
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at src/mp4.rs:1024
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at src/mp4.rs:923
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: 11: moonfire_nvr::mp4::FileBuilder::build
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at src/mp4.rs:856
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: 12: moonfire_nvr::web::ServiceInner::camera_view_mp4
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at src/web.rs:378
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: 13: <tokio_proto::streaming::pipeline::server::Dispatch<S, T, P> as tokio_proto::streaming::pipeline::advanced::Dispatch>::dispatch
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at src/web.rs:467
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/git/checkouts/hyper-d300147022600c0c/c038b24/src/server/mod.rs:480
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/git/checkouts/hyper-d300147022600c0c/c038b24/src/server/mod.rs:335
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/server.rs:124
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: 14: <tokio_proto::streaming::pipeline::advanced::Pipeline<T> as futures::future::Future>::poll
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/advanced.rs:171
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/advanced.rs:121
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/advanced.rs:376
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: 15: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/future/chain.rs:42
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/future/and_then.rs:32
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/future/map_err.rs:30
Mar  9 23:24:26 moonfire moonfire-nvr[19022]: 16: tokio_core::reactor::Core::poll
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/future/mod.rs:113
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/mod.rs:289
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/mod.rs:350
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/std/mod.rs:79
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/mod.rs:350
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/mod.rs:289
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.9/src/reactor/mod.rs:356
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.9/src/reactor/mod.rs:355
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.9/src/reactor/mod.rs:316
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.9/src/reactor/mod.rs:304
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.9/src/reactor/mod.rs:241
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./home/pi/.cargo/git/checkouts/hyper-d300147022600c0c/c038b24/src/server/mod.rs:425
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at src/cmds/run.rs:142
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: 18: moonfire_nvr::main
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at src/main.rs:144
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: 19: __rust_maybe_catch_panic
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./checkout/src/libpanic_unwind/lib.rs:99
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: 20: std::rt::lang_start
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panicking.rs:459
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/panic.rs:361
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: at ./checkout/src/libstd/rt.rs:61
Mar  9 23:24:28 moonfire moonfire-nvr[19022]: 21: __libc_start_main
Mar  9 23:24:28 moonfire systemd[1]: moonfire-nvr.service: main process exited, code=exited, status=101/n/a
Mar  9 23:24:28 moonfire systemd[1]: Unit moonfire-nvr.service entered failed state.
```

**Comment by scottlamb** [comment]
Looks like that happens when you hit `.../view.mp4` without specifying any segments. I think this used to work; I probably broke it with 04e9f3f1.
